version: "3.8"
services:
  nodeserver:
    build:
      context: ../../server
    ports:
      - "8000:8000"
  nginx:
    restart: always
    build:
      context: ../nginx/server
    ports:
      - "80:80"
